### ISSUE TITLE
deprecation warning in addSlash redirects

### ISSUE THREAD

**Issue by warner** [twisted/nevow#52]
While investigating https://tahoe-lafs.org/trac/tahoe-lafs/ticket/2312 , I found that Nevow-0.11.1 plus Twisted-13.0.0 plus python-2.6 can provoke an annoying DeprecationWarning, if you use a nevow.rend.Page with `addSlash = True` and then render the page in a way that forces a redirect to self-plus-slash.

It looks like twisted.web.http.Request.setHeader() used to accept anything string-able, but now insists upon actual "bytes" objects (probably to avoid confusing unicode errors), and emits a DeprecationWarning if it gets otherwise. We had one place in Tahoe where we used `req.setHeader("content-length", len(body))`, which ran afoul of this.

But there's another one in nevow itself, in `nevow.rend.Page._renderHTTP`, where the addSlash behavior is implemented with:

    request.redirect(request.URLPath().child(''))

That passes a URL object into `setHeader("location", url)`, which triggers the same warning. I haven't tried making a short proof-of-concept, or tried running Nevow's tests against py2.6.

We don't see this when testing under python2.7, probably because 2.7 does something foolish like disabling all DeprecationWarnings. I haven't done exhaustive testing, but if that's really true, I suspect it'll be a big problem for libraries that want to signal their own deprecations to higher-layer apps (Twisted uses DeprecationWarnings extensively).

I think the fix will be to replace that code in `_renderHTTP` with something like:

    request.redirect(str(request.URLPath().child('')))

**Comment by mithrandi** [comment]
Firstly, while I haven't yet had a chance to look at the code, your diagnosis and fix of the issue seem plausible and correct.

Regarding warnings: `DeprecationWarning` is ignored by default in Python 2.7. As the usual audience of warnings in a Python program (the user) is unable to do anything about them, this is a reasonable choice, but unfortunately rather confusing / problematic for developers who are unaware of this change. Run your tests with something like `python -W default::DeprecationWarning` or `python -W error::DeprecationWarning` (or set `$PYTHONWARNINGS`) in order to see them when testing.

Regarding `twisted.web` and `unicode`: the interface that `setHeader` and `write` previously accepted was the `buffer` interface, not "anything string-able". This meant that doing `setHeader('something', u'hi')` would produce data in the header like "something: h\x00\x\00\x00i\x00\x00\x00" due to the behaviour of the buffer interface for the unicode type (it just exposes the UTF-32 or UTF-16 bytes), with predicably confusing and hard-to-diagnose results.

**Comment by warner** [comment]
Ah, thanks, I keep forgetting that `DeprecationWarning` is aimed at developers, not users, and that $PYTHONWARNINGS is involved. I'll set that on our tests.
